export const ADD_TO_CART = "ADD_TO_CART";

export const REMOVE_CART_ITEM = "REMOVE_CART_ITEM";

export const SAVE_SHIPPING_INFO = "SAVE_SHIPPING_INFO";


export const LOAD_USER_CART = "LOAD_USER_CART";

export const LOAD_USER_SHIPPING_INFO = "LOAD_USER_SHIPPING_INFO";